import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme={"light"}>
    <body className={`bg-base-100 scrollBar`}>{children}</body>
    </html>
  );
}
